export enum ExerciseType {
  Duration = 'Barbell',
  Distance = 'Dumbbell',
  Bodyweight = 'Bodyweight',
  Machine = 'Machine',
}

export enum Exercise {
  Bench = 'Bench Press',
  InclineBench = 'Incline Press',
  InclineDumbbellBench = 'Incline Dumbbell Bench',
  DumbbellBench = 'Flat Dumbbell Bench',
  Press = 'Press',
  DumbbellPress = 'Dumbbell Press',
  CloseGripBench = 'Close Grip Bench Press',
  LateralRaises = 'Lateral Raises',
  OneArmLateralRaises = 'One Arm Cable Lateral Raises',
  DiamondPushUp = 'Diamond Pushups',
  Flyes = 'Flyes',
  InclineFlyes = 'Incline DB Chest Flyes',
  MachineChestPress = 'Machine Chest Press',
  BehindNeckPress = 'Behind-the-Neck Overhead Press',

  Deadlift = 'Deadlift',
  RDL = 'Romanian Deadlift',
  Squat = 'Squat',
  FrontSquat = 'Front Squat',
  Hyperextensions = 'Hyperextensions',
  GoodMorning = 'Good Mornings',
  LegPress = 'Leg Press',
  LegCurls = 'Leg Curls',
  LegExtensions = 'Leg Extensions',
  BulgarianSplitSquat = 'Bulgarian Split Squats',
  RomanianDeadlift = ' Romanian Deadlifts',
  Calfs = 'Calf Raises',
  HackSquats = 'Hack Squats',
  Lunge = 'Lunge',

  Curl = 'Curls',
  InclineCurls = 'Incline Curls',
  PreacherCurl = 'Preacher Curl',
  TricepExtensions = 'Tricep Extensions',
  Skullcrushers = 'Skullcrushers',
  HammerCurl = 'Hammer Curls',
  DBSkulls = 'Dumbbell Skullcrushers',
  TricepRopePushdowns = 'Tricep Rope Pushdowns',
  Kickbacks = 'Tricep Cable Kickbacks',
  ConcentrationCurl = 'Conentration Curl',
  SpiderCurls = 'Spider Curls',
  DragCurl = 'Drag Curls',

  Row = 'Row',
  DumbbellRow = 'Dumbbell Row',
  Shrugs = 'Shrugs',
  CableRow = 'Seated Cable Row',
  Pulldowns = 'Pulldowns',
  RackChins = 'Rack Chins',

  MultiLunge = 'Multi Directional Lunge',
  ReverseLunge = 'Reverse Lunge',
  WalkingLunges = 'Walking Lunges',
  HipThrust = 'Hip Thrusts',
  HipBand = 'Hip Bands Side Steps',

  Facepull = 'Face pulls',
  PullApart = 'Band Pull Aparts',
  HighPulls = 'Dumbbell High Pulls / Upright Rows',

  Pullup = 'Pull Ups',
  Chinup = 'Chin Ups',
  Pushup = 'Push Ups',
  Dip = 'Dips',
  MuscleUp = 'Muscle Ups',
  HandstandPushup = 'Handstand Pushups',

  CableCrunches = 'Cable Crunches',
  Situp = 'Sit Up',
  LegRaises = 'Leg Raises',
  AbWheel = 'Ab Wheel',
  AlternatingLegRaises = 'Alternating Leg Raises',
  TurkishGetUp = 'Turkish Get Ups',

  PowerClean = 'Power Clean',
  PowerSnatch = 'Power Snatch',

  MileRun = 'Mile Run',
  FiveKmRun = '5k Run',

  DbCarry = 'Dumbbell Carry',
  DbOverheadCarry = 'Dumbbell Ovehead Carry',
}
